### ISSUE TITLE
Throughput values & unroll factors

### ISSUE THREAD

**Issue by dlrauch15** [ithemal/bhive#2]
Hello,

I was hoping to get some clarification into the throughput values in your dataset. The BHive paper says that throughput is calculated as follows:

throughput(b) ≈ (cycles(b, n) − cycles(b, n')) / (n − n')

Where _b_ is the BB and _n_, _n'_ are the two unroll factors.

The first basic block and throughput value in `throughput/skl.csv` is:
`4183ff0119c083e00885c98945c4b8010000000f4fc139c2,249.000000`

The reported throughput is 249 but it doesn't appear that this is ever divided by the difference in the unroll factors. When I run this basic block through the profiler on my machine (Intel Coffee Lake), I get 963 and 1214 cycles for unroll factors of 100 and 200, respectively. The difference is 251, very close to the 249 in your dataset.

Shouldn't the reported throughput for this BB be 2.49 instead of 249?

I thought that perhaps the dividing by the difference in unroll factors was performed at a later step when using this data set, but there's also this BB:

`42a010000c784242c0100000000000048c784243001000000000000c6842438010000006644899c240a01000048c7842458010000000000004c89b424500100004889ac24400100004489a424480100004889842460010000,2087.500000`

This throughput value is not an integer, so clearly there is some division going on.

Could you please provide clarification on how the exact throughput values in the csv files are calculated? Also, would it be possible to see the script/program that generated these CSV files? I've looked through the timing-harness repo, but this only has a script for measuring throughput for a single BB, not every BB in your dataset.

Thanks so much for your help!

**Comment by ychen306** [comment]
All throughput is normalized for 100 reps. 

You can see fractional throughput because we don't unroll large basic block by 100 iterations when we measure them (otherwise the unrolled block doesn't fit in the instruction cache). For these we use different unroll factors (e.g., 32 and 16).
